name = input("What's your name?")
print(name)
print(name)
print(name)
print(name)
print(name)

age = input("How old are you?")
print(age)
print(age)
print(age)
print(age)
print(age)

birth = input("When is your birthday?")
print(birth)
print(birth)
print(birth)
print(birth)
print(birth)