# versionを指定している
version: "3"
services:
    web:
        image: httpd
        # volumesでファイルの中身をimportしている
        volumes:
            - ./html:/usr/local/apache2/htdocs
            - httpd-data:/usr/local/apache2/conf
        ports:
            - "8080:80"
# volumesを読み込む（永続化されたデータ？）
volumes:
        httpd-data:
