# versionを指定している
version: "3"
services:
    web:
        # imageを選択して仮想空間内にそのimageを使って空間を構築している
        image: httpd
        # volumesでファイルの中身をimportしている
        volumes:
            - ./html:/usr/local/apache2/htdocs
            - httpd-data:/usr/local/apache2/conf
        ports:
            - "8080:80"
# volumesを読み込む（永続化されたデータ？）なんかパソコンが落ちた時にもずっと稼働する）
volumes:
        httpd-data:
