version: "3"
services:
    web:
        image: httpd
        # volumesでファイルを入れている
        volumes:
            - ./html:/usr/local/apache2/htdocs
            - httpd-data:/usr/local/apache2/conf
        ports:
            - "8080:80"
volumes:
        httpd-data:
