version: '3.8'
services:
  web:
    # platformを追加したらバグが出るので注意
    # platform: linux/x86_64
    build: ./flask
    volumes:
      - ./flask:/app
    # web appを開くportを指定
    ports:
      - 5000:5000
    links:
      - db
    tty: true
    environment:
      # timezoneを東京に変える作業
      TZ: Asia/Tokyo
      FLASK_APP: app.py
      FLASK_ENV: development
    command: flask run -h 0.0.0.0 --port 5000
  db:
    # platform書くとエラーが起きちゃうどん
    # platform: linux/x86_64
    build: ./db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: flask
      MYSQL_USER: flask
      MYSQL_PASSWORD: flask
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
    volumes:
      - ./initdb.d:/docker-entrypoint-initdb.d
      - ./db/data:/var/lib/mysql
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./db/init:/docker-entrypoint-initdb.d
      - ./db/log:/var/log/mysql
    # portを指定
    ports:
      - 3030:3030
