version: "3.8"

services:
  db:
    container_name: db
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    ports:
      - 1180:1180
    env_file:
      - ./.env_mysql
    volumes:
      - type: volume
        source: mysql-data
        target: /var/lib/mysql
      - type: bind
        source: ./init
        target: /docker-entrypoint-initdb.d

  web:
      build: .
      command: python3 app/app.py
      volumes:
          - ./app:/app
      ports:
          - 3000:3000


volumes:
  mysql-data:
    name: mysql-volume